# PANDAS - 2 Additional_Excercise_6.11442

#### Get Data from the following link: http://files.grouplens.org/datasets/movielens/ml-20m.zip
#### We will be using the following files for this exercise
    #### ratings.csv : userId,movieId,rating, timestamp
    #### tags.csv : userId,movieId, tag, timestamp
    #### movies.csv : movieId, title, genres

#### 1. Read the dataset using pandas.

In [1]:
import pandas as pd

In [2]:
ratings = pd.read_csv('ratings.csv')
tags = pd.read_csv('tags.csv')
movies = pd.read_csv('movies.csv')

In [3]:
ratings.head()

   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [4]:
tags.head()

   userId  movieId            tag   timestamp
0      18     4141    Mark Waters  1240597180
1      65      208      dark hero  1368150078
2      65      353      dark hero  1368150079
3      65      521  noir thriller  1368149983
4      65      592      dark hero  1368150078

In [5]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
ratings.info()
print()
tags.info()
print()
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 4 columns):
userId       int64
movieId      int64
rating       float64
timestamp    int64
dtypes: float64(1), int64(3)
memory usage: 610.4 MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465564 entries, 0 to 465563
Data columns (total 4 columns):
userId       465564 non-null int64
movieId      465564 non-null int64
tag          465548 non-null object
timestamp    465564 non-null int64
dtypes: int64(3), object(1)
memory usage: 14.2+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
movieId    27278 non-null int64
title      27278 non-null object
genres     27278 non-null object
dtypes: int64(1), object(2)
memory usage: 639.4+ KB

#### 2. Extract the first row from tags and print its type.

In [22]:
tags.iloc[0]

userId                18
movieId             4141
tag          Mark Waters
timestamp     1240597180
Name: 0, dtype: object

##### 3. Extract row 0, 11, 2000 from tags DataFrame.

In [26]:
tags.loc[[0,11,2000]]

      userId  movieId                tag   timestamp
0         18     4141        Mark Waters  1240597180
11        65     1783      noir thriller  1368149983
2000     910    68554  conspiracy theory  1368043943

#### 4. Print index, columns of the DataFrame.

In [28]:
movies.index

RangeIndex(start=0, stop=27278, step=1)

In [29]:
movies.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [32]:
tags.index

RangeIndex(start=0, stop=465564, step=1)

In [33]:
tags.columns

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [34]:
ratings.index

RangeIndex(start=0, stop=20000263, step=1)

In [35]:
ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

#### 5. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().

In [36]:
ratings['rating'].describe()

count    2.000026e+07
mean     3.525529e+00
std      1.051989e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [37]:
ratings.groupby('rating').describe()

          movieId                                                           \
            count          mean           std  min     25%     50%     75%
rating
0.5      239125.0  13356.246729  23540.155879  1.0  1468.0  3552.0  7004.0
1.0      680732.0   5652.208219  14579.586860  1.0   704.0  2053.0  3688.0
1.5      279252.0  12377.773230  22686.931146  1.0  1405.0  3261.0  6629.0
2.0     1430997.0   6733.595232  16488.702470  1.0   783.0  2143.0  3916.0
2.5      883398.0  13669.268192  24030.549420  1.0  1500.0  3499.0  7036.0
3.0     4291193.0   6770.763264  17060.805484  1.0   548.0  1735.0  3704.0
3.5     2200156.0  14814.098703  24964.575966  1.0  1479.0  3624.0  7502.0
4.0     5561926.0   8342.514461  18921.333278  1.0   904.0  2054.0  4232.0
4.5     1534824.0  14585.414824  24569.051130  1.0  1252.0  3448.0  7502.0
5.0     2898660.0   6275.356017  16245.763837  1.0   662.0  1321.0  3275.0

                  timestamp                  ...                   \
             max      count          mean    ...              75%
rating                                       ...
0.5     131152.0   239125.0  1.209060e+09    ...     1.286736e+09
1.0     131172.0   680732.0  1.043247e+09    ...     1.128350e+09
1.5     131060.0   279252.0  1.200202e+09    ...     1.271984e+09
2.0     131162.0  1430997.0  1.064063e+09    ...     1.162872e+09
2.5     131258.0   883398.0  1.203932e+09    ...     1.281103e+09
3.0     131260.0  4291193.0  1.046027e+09    ...     1.161513e+09
3.5     131231.0  2200156.0  1.210879e+09    ...     1.290326e+09
4.0     131262.0  5561926.0  1.082045e+09    ...     1.207570e+09
4.5     131176.0  1534824.0  1.217216e+09    ...     1.300060e+09
5.0     131050.0  2898660.0  1.055206e+09    ...     1.174082e+09

                         userId                                             \
                 max      count          mean           std   min      25%
rating
0.5     1.427771e+09   239125.0  68273.393903  39717.578126  11.0  34103.0
1.0     1.427771e+09   680732.0  69266.000782  40173.814049   3.0  34222.0
1.5     1.427779e+09   279252.0  69305.992867  40018.666604  11.0  34350.0
2.0     1.427781e+09  1430997.0  68996.772884  40096.229985   2.0  34098.0
2.5     1.427782e+09   883398.0  68643.592418  40009.623383  11.0  33841.0
3.0     1.427782e+09  4291193.0  69074.100455  40083.321744   1.0  34289.0
3.5     1.427784e+09  2200156.0  68841.218349  39978.319652   1.0  34202.0
4.0     1.427782e+09  5561926.0  69138.370810  40061.666257   1.0  34557.0
4.5     1.427781e+09  1534824.0  69053.127449  39948.507340   1.0  34570.0
5.0     1.427781e+09  2898660.0  69111.904239  39996.382873   1.0  34604.0


            50%        75%       max
rating
0.5     68060.0  102570.00  138493.0
1.0     69793.0  103943.00  138493.0
1.5     69716.0  103702.00  138492.0
2.0     69268.0  103546.00  138493.0
2.5     68653.0  103195.00  138493.0
3.0     69282.0  103704.00  138493.0
3.5     68653.0  103348.00  138493.0
4.0     69234.0  103729.75  138493.0
4.5     69048.0  103544.00  138493.0
5.0     69219.0  103654.00  138493.0

[10 rows x 24 columns]

#### 6. Filter out ratings with rating > 5

In [42]:
ratings[ratings['rating']>5]
# 5 is the maximum rating and there are no values in dataframe having rating greater then 5, hence output return nothing

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

#### 7. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.

In [56]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [58]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [71]:
# finding NaN value at dataframe
tags.isnull().sum()

userId        0
movieId       0
tag          16
timestamp     0
dtype: int64

In [67]:
#checking NaN value at column level
tags[tags['tag'].isnull()]

        userId  movieId  tag   timestamp
373276  116460      123  NaN  1199450867
373277  116460      346  NaN  1199451946
373281  116460     1184  NaN  1199452261
373288  116460     1785  NaN  1199452006
373289  116460     2194  NaN  1199450677
373291  116460     2691  NaN  1199451002
373299  116460     4103  NaN  1199451920
373301  116460     4473  NaN  1199451040
373303  116460     4616  NaN  1199452441
373319  116460     7624  NaN  1199452266
373325  116460     8898  NaN  1199450757
373332  116460    32460  NaN  1199450901
373334  116460    33826  NaN  1199450703
373339  116460    36537  NaN  1199450736
373340  116460    55805  NaN  1199450941
454615  133634    33826  NaN  1221450908

In [73]:
#axis 1 = column axis 0 = row
tags.fillna(value='Not Provided',axis=0,inplace=True)

In [75]:
tags.isnull().sum()

userId       0
movieId      0
tag          0
timestamp    0
dtype: int64

#### 8. Filter out movies from the movies DataFrame that are of type 'Animation'.

In [86]:
movies[movies['genres'] == 'Animation']

       movieId                                              title     genres
2503      2588                                   Cloudland (1998)  Animation
4906      5002                               Fritz the Cat (1972)  Animation
4907      5003            Nine Lives of Fritz the Cat, The (1974)  Animation
9455     27738                    Cathedral, The (Katedra) (2002)  Animation
9989     32840                                     Vincent (1982)  Animation
13444    66335                  Afro Samurai: Resurrection (2009)  Animation
13858    69469                        Garfield's Pet Force (2009)  Animation
14184    71158                Immigrants (L.A. Dolce Vita) (2008)  Animation
14492    72603                            Merry Madagascar (2009)  Animation
14578    72927                                 Donkey Xote (2007)  Animation
14580    72931                                       Tango (1981)  Animation
14876    74486                                       $9.99 (2008)  Animation
14938    74791   Town Called Panic, A (Panique au village) (2009)  Animation
15085    76709   Spider-Man: The Ultimate Villain Showdown (2002)  Animation
15860    80469                 Superman/Batman: Apocalypse (2010)  Animation
15990    81018          Illusionist, The (L'illusionniste) (2010)  Animation
16551    83603             Fern flowers (Fleur de fougère) (1949)  Animation
16649    84192  Corto Maltese: Ballad of the Salt Sea (Corto M...  Animation
18144    90843  Lavatory Lovestory (Ubornaya istoriya - lyubov...  Animation
18145    90845  Fall of the House of Usher, The (Zánik domu Us...  Animation
18224    91187                                   Millhaven (2010)  Animation
18695    93083                                  Live Music (2009)  Animation
18980    94423  Disney Princess Collection: Jasmine's Enchante...  Animation
19562    96897  Bleach: Fade to Black (Bur&#299;chi Fade to Bl...  Animation
20310    99820  Pokémon the Movie: Black - Victini and Reshira...  Animation
20311    99822  Pokémon the Movie: White - Victini and Zekrom ...  Animation
20314    99832                            Hand, The (Ruka) (1966)  Animation
20527   100509               Tale of Tales (Skazka skazok) (1979)  Animation
20871   102007                    Invincible Iron Man, The (2007)  Animation
20872   102009                       Thor: Tales of Asgard (2011)  Animation
...        ...                                                ...        ...
25207   118948                                   Blackbird (1959)  Animation
25208   118950                                  A Phantasy (1952)  Animation
25211   118956                           Lines: Horizontal (1962)  Animation
25212   118958                                      Mosaic (1966)  Animation
25213   118960                            Begone Dull Care (1949)  Animation
25214   118962                                   Synchromy (1971)  Animation
25538   120853                             Fresh Guacamole (2012)  Animation
25539   120855                                Adam and Dog (2012)  Animation
25663   121302                              Someone's Gaze (2013)  Animation
25718   121600                       Bosko's Parlor Pranks (1934)  Animation
26052   124889    The Adventures of Tom Thumb & Thumbelina (2002)  Animation
26163   125924                           The Periwig-Maker (1999)  Animation
26169   125936                                        Crac (1981)  Animation
26171   125940                                      Syrinx (1966)  Animation
26181   125960                     The Trip to Squash Land (1967)  Animation
26185   125968     It's Christmastime Again, Charlie Brown (1992)  Animation
26189   125976                       Nocturna Artificialia (1979)  Animation
26192   125982                              Trick or Treat (1952)  Animation
26207   126012            The Fat Albert Halloween Special (1977)  Animation
26226   126050                    Stille Nacht I: Dramolet (1988)  Animation
26230   126058            Rehearsals for Extinct Anatomies (1987)  Animation
26236   126070                               Chainsaw Maid (2007)  Animation
26237   126072                        The Little Matchgirl (2006)  Animation
26246   126090                         Hedgehog in the Fog (1975)  Animation
26247   126092                               The Cat's Out (1931)  Animation
26248   126094                Claymation Comedy of Horrors (1991)  Animation
26319   126405        The Adventures of André and Wally B. (1984)  Animation
26809   128864                              Four Sahibjade (2014)  Animation
27103   130394                                  The Mascot (1934)  Animation
27155   130644  The Garden of Sinners - Chapter 5: Paradox Par...  Animation

[83 rows x 3 columns]

#### 9. Find the average rating of movies.

In [92]:
ratings['rating'].mean()

3.5255285642993797

#### 10. Perform an inner join of movies and tags based on movieId.

In [99]:
movies.join(tags,on=['movieId'],how='inner',lsuffix='_movies',rsuffix='_tags')

,movieId,movieId_movies,title,genres,userId,movieId_tags,tag,timestamp
0,1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,65,208,dark hero,1368150078
1,2,2,Jumanji (1995),Adventure|Children|Fantasy,65,353,dark hero,1368150079
2,3,3,Grumpier Old Men (1995),Comedy|Romance,65,521,noir thriller,1368149983
3,4,4,Waiting to Exhale (1995),Comedy|Drama|Romance,65,592,dark hero,1368150078
4,5,5,Father of the Bride Part II (1995),Comedy,65,668,bollywood,1368149876
5,6,6,Heat (1995),Action|Crime|Thriller,65,898,screwball comedy,1368150160
6,7,7,Sabrina (1995),Comedy|Romance,65,1248,noir thriller,1368149983
7,8,8,Tom and Huck (1995),Adventure|Children,65,1391,mars,1368150055
8,9,9,Sudden Death (1995),Action,65,1617,neo-noir,1368150217
9,10,10,GoldenEye (1995),Action|Adventure|Thriller,65,1694,jesus,1368149925
10,11,11,"American President, The (1995)",Comedy|Drama|Romance,65,1783,noir thriller,1368149983
11,12,12,Dracula: Dead and Loving It (1995),Comedy|Horror,65,2022,jesus,1368149925
12,13,13,Balto (1995),Adventure|Animation|Children,65,2193,dragon,1368151314
13,14,14,Nixon (1995),Drama,65,2353,conspiracy theory,1368151266
14,15,15,Cutthroat Island (1995),Action|Adventure|Romance,65,2662,mars,1368150055
15,16,16,Casino (1995),Crime|Drama,65,2726,noir thriller,1368149983
16,17,17,Sense and Sensibility (1995),Drama|Romance,65,2840,jesus,1368149925
17,18,18,Four Rooms (1995),Comedy,65,3052,jesus,1368149926
18,19,19,Ace Ventura: When Nature Calls (1995),Comedy,65,5135,bollywood,1368149876
19,20,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,65,6539,treasure,1368149949
20,21,21,Get Shorty (1995),Comedy|Crime|Thriller,65,6874,dark hero,1368150079
21,22,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,65,7013,noir thriller,1368149983
22,23,23,Assassins (1995),Action|Crime|Thriller,65,7318,jesus,1368149925
23,24,24,Powder (1995),Drama|Sci-Fi,65,8529,stranded,1368150012
24,25,25,Leaving Las Vegas (1995),Drama|Romance,65,8622,conspiracy theory,1368151266
25,26,26,Othello (1995),Drama,65,27803,Oscar (Best Foreign Language Film),1305008715
26,27,27,Now and Then (1995),Children|Drama,65,27866,New Zealand,1304957153
27,28,28,Persuasion (1995),Drama|Romance,65,48082,surreal,1304958354
28,29,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,65,48082,unusual,1304958359
29,30,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,65,51884,bollywood,1368149876
...,...,...,...,...,...,...,...,...
27248,131146,131146,Werner - Volles Rooäää (1999),Animation|Comedy,34494,53956,Nudity (Rear),1326402278
27249,131148,131148,What A Man (2011),Comedy|Romance,34494,53956,wheelchair,1326402295
27250,131150,131150,7 Dwarves: The Forest Is Not Enough (2006),Comedy,34494,56719,prodigy,1326535978
27251,131152,131152,The Fat Spy (1966),Comedy,34494,58998,break-up,1327260156
27252,131154,131154,"Die Bademeister – Weiber, saufen, Leben retten...",Comedy,34494,58998,Hawaii,1327260176
27253,131156,131156,Ants in the Pants 2 (2002),Comedy,34494,58998,jealousy,1327260186
27254,131158,131158,"Manta, Manta (1991)",Comedy,34494,58998,Nudity (Full Frontal - Notable),1327260193
27255,131160,131160,Oscar and the Lady in Pink (2009),Drama,34494,58998,puppets,1327260247
27256,131162,131162,Por un puñado de besos (2014),Drama|Romance,34494,58998,surfing,1327260243
27257,131164,131164,Vietnam in HD (2011),War,34494,60069,Comedy,1322934956
27258,131166,131166,WWII IN HD (2009),(no genres listed),34494,60069,robots,1322934947
27259,131168,131168,Phoenix (2014),Drama,34494,60408,hilarious,1322934874
27260,131170,131170,Parallels (2015),Sci-Fi,34494,61323,Brad Pitt,1326646054
27261,131172,131172,Closed Curtain (2013),(no genres listed),34494,61323,cosmetic surgery,1326646075
27262,131174,131174,Gentlemen (2014),Drama|Romance|Thriller,34494,61323,George Clooney,1326646092
27263,131176,131176,A Second Chance (2014),Drama,34494,61323,John Malkovich,1326646067
27264,131180,131180,Dead Rising: Watchtower (2015),Action|Horror|Thriller,34494,64614,Clint Eastwood,1323542837
27265,131231,131231,Standby (2014),Comedy|Romance,34494,73587,sexuality,1323469711
27266,131237,131237,What Men Talk About (2010),Comedy,34494,76093,dragons,1325326591
27267,131239,131239,Three Quarter Moon (2011),Comedy|Drama,34494,76093,friendship,1325326636
27268,131241,131241,Ants in the Pants (2000),Comedy|Romance,34494,77191,dark comedy,1326402404
27269,131243,131243,Werner - Gekotzt wird später (2003),Animation|Comedy,34494,77191,male nudity,1326402427
27270,131248,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy,34494,78321,sexuality,1326228885
27271,131250,131250,No More School (2000),Comedy,34494,79132,alternate reality,1325326442
27272,131252,131252,Forklift Driver Klaus: The First Day on the Jo...,Comedy|Horror,34494,79132,dreamlike,1325326562
27273,131254,131254,Kein Bund für's Leben (2007),Comedy,34494,79132,fantasy,1325326456
27274,131256,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,34494,79132,Leonardo DiCaprio,1325326461
27275,131258,131258,The Pirates (2014),Adventure,34494,79132,sci-fi,1325326474
27276,131260,131260,Rentun Ruusu (2001),(no genres listed),34494,79132,thought-provoking,1325326483
27277,131262,131262,Innocence (2014),Adventure|Fantasy|Horror,34494,79590,AGE DISPARITY ROMANCE,1326319089

#### Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.

In [122]:
movietagrating = pd.concat([movies,tags,ratings],axis=1,join='inner')
movietagrating[(movietagrating['genres']=='Comedy') & (movietagrating['rating'] > 4)]['title'][:5]

142                        Brothers McMullen, The (1995)
185                                    Party Girl (1995)
201    To Wong Foo, Thanks for Everything! Julie Newm...
220                                        Clerks (1994)
231                                  Exit to Eden (1994)
Name: title, dtype: object

#### 12. Split 'genres' into multiple columns.

In [170]:
movies['genres'].str.split("|", n=4,expand = True)

                        0          1         2        3         4
0               Adventure  Animation  Children   Comedy   Fantasy
1               Adventure   Children   Fantasy     None      None
2                  Comedy    Romance      None     None      None
3                  Comedy      Drama   Romance     None      None
4                  Comedy       None      None     None      None
5                  Action      Crime  Thriller     None      None
6                  Comedy    Romance      None     None      None
7               Adventure   Children      None     None      None
8                  Action       None      None     None      None
9                  Action  Adventure  Thriller     None      None
10                 Comedy      Drama   Romance     None      None
11                 Comedy     Horror      None     None      None
12              Adventure  Animation  Children     None      None
13                  Drama       None      None     None      None
14                 Action  Adventure   Romance     None      None
15                  Crime      Drama      None     None      None
16                  Drama    Romance      None     None      None
17                 Comedy       None      None     None      None
18                 Comedy       None      None     None      None
19                 Action     Comedy     Crime    Drama  Thriller
20                 Comedy      Crime  Thriller     None      None
21                  Crime      Drama    Horror  Mystery  Thriller
22                 Action      Crime  Thriller     None      None
23                  Drama     Sci-Fi      None     None      None
24                  Drama    Romance      None     None      None
25                  Drama       None      None     None      None
26               Children      Drama      None     None      None
27                  Drama    Romance      None     None      None
28              Adventure      Drama   Fantasy  Mystery    Sci-Fi
29                  Crime      Drama      None     None      None
...                   ...        ...       ...      ...       ...
27248           Animation     Comedy      None     None      None
27249              Comedy    Romance      None     None      None
27250              Comedy       None      None     None      None
27251              Comedy       None      None     None      None
27252              Comedy       None      None     None      None
27253              Comedy       None      None     None      None
27254              Comedy       None      None     None      None
27255               Drama       None      None     None      None
27256               Drama    Romance      None     None      None
27257                 War       None      None     None      None
27258  (no genres listed)       None      None     None      None
27259               Drama       None      None     None      None
27260              Sci-Fi       None      None     None      None
27261  (no genres listed)       None      None     None      None
27262               Drama    Romance  Thriller     None      None
27263               Drama       None      None     None      None
27264              Action     Horror  Thriller     None      None
27265              Comedy    Romance      None     None      None
27266              Comedy       None      None     None      None
27267              Comedy      Drama      None     None      None
27268              Comedy    Romance      None     None      None
27269           Animation     Comedy      None     None      None
27270           Adventure  Animation  Children   Comedy   Fantasy
27271              Comedy       None      None     None      None
27272              Comedy     Horror      None     None      None
27273              Comedy       None      None     None      None
27274              Comedy       None      None     None      None
27275           Adventure       None      None     None      None
27276  (no genres listed)       None      None     None      None
27277           Adventure    Fantasy    Horror     None      None

[27278 rows x 5 columns]

#### 13. Extract year from title e.g. (1995).

In [224]:
def extractyear(string):
    year=''
    for char in string:
        if char.isdigit():
            year=year+char
    return year

movies['year']=movies['title'].apply(extractyear)
movies.head()

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995

#### 14. Select rows based on timestamps later than 2015-02-01.

In [258]:
tags['date'] = pd.to_datetime(tags['timestamp'])

In [260]:
tags[tags['date']<'2015-02-01']

,userId,movieId,tag,timestamp,date
0,18,4141,Mark Waters,1240597180,1970-01-01 00:00:01.240597180
1,65,208,dark hero,1368150078,1970-01-01 00:00:01.368150078
2,65,353,dark hero,1368150079,1970-01-01 00:00:01.368150079
3,65,521,noir thriller,1368149983,1970-01-01 00:00:01.368149983
4,65,592,dark hero,1368150078,1970-01-01 00:00:01.368150078
5,65,668,bollywood,1368149876,1970-01-01 00:00:01.368149876
6,65,898,screwball comedy,1368150160,1970-01-01 00:00:01.368150160
7,65,1248,noir thriller,1368149983,1970-01-01 00:00:01.368149983
8,65,1391,mars,1368150055,1970-01-01 00:00:01.368150055
9,65,1617,neo-noir,1368150217,1970-01-01 00:00:01.368150217
10,65,1694,jesus,1368149925,1970-01-01 00:00:01.368149925
11,65,1783,noir thriller,1368149983,1970-01-01 00:00:01.368149983
12,65,2022,jesus,1368149925,1970-01-01 00:00:01.368149925
13,65,2193,dragon,1368151314,1970-01-01 00:00:01.368151314
14,65,2353,conspiracy theory,1368151266,1970-01-01 00:00:01.368151266
15,65,2662,mars,1368150055,1970-01-01 00:00:01.368150055
16,65,2726,noir thriller,1368149983,1970-01-01 00:00:01.368149983
17,65,2840,jesus,1368149925,1970-01-01 00:00:01.368149925
18,65,3052,jesus,1368149926,1970-01-01 00:00:01.368149926
19,65,5135,bollywood,1368149876,1970-01-01 00:00:01.368149876
20,65,6539,treasure,1368149949,1970-01-01 00:00:01.368149949
21,65,6874,dark hero,1368150079,1970-01-01 00:00:01.368150079
22,65,7013,noir thriller,1368149983,1970-01-01 00:00:01.368149983
23,65,7318,jesus,1368149925,1970-01-01 00:00:01.368149925
24,65,8529,stranded,1368150012,1970-01-01 00:00:01.368150012
25,65,8622,conspiracy theory,1368151266,1970-01-01 00:00:01.368151266
26,65,27803,Oscar (Best Foreign Language Film),1305008715,1970-01-01 00:00:01.305008715
27,65,27866,New Zealand,1304957153,1970-01-01 00:00:01.304957153
28,65,48082,surreal,1304958354,1970-01-01 00:00:01.304958354
29,65,48082,unusual,1304958359,1970-01-01 00:00:01.304958359
...,...,...,...,...,...
465534,138436,81932,big hair,1298754654,1970-01-01 00:00:01.298754654
465535,138436,81932,Mark Wahlberg,1298754636,1970-01-01 00:00:01.298754636
465536,138436,81932,pigs,1298754658,1970-01-01 00:00:01.298754658
465537,138436,81932,prostitution,1298754620,1970-01-01 00:00:01.298754620
465538,138437,77154,"This movie should have been called ""How Cocain...",1357384633,1970-01-01 00:00:01.357384633
465539,138446,317,Christmas,1358983914,1970-01-01 00:00:01.358983914
465540,138446,317,funny,1358983914,1970-01-01 00:00:01.358983914
465541,138446,317,Judge Reinhold,1358983914,1970-01-01 00:00:01.358983914
465542,138446,317,Tim Allen,1358983914,1970-01-01 00:00:01.358983914
465543,138446,317,whiny kid,1358983946,1970-01-01 00:00:01.358983946
465544,138446,837,family friendly,1358983693,1970-01-01 00:00:01.358983693
465545,138446,918,halloween scene,1358984062,1970-01-01 00:00:01.358984062
465546,138446,918,quirky,1358984051,1970-01-01 00:00:01.358984051
465547,138446,2396,topless scene,1358973995,1970-01-01 00:00:01.358973995
465548,138446,3086,Christmas,1358983979,1970-01-01 00:00:01.358983979
465549,138446,3086,classic,1358983979,1970-01-01 00:00:01.358983979
465550,138446,3086,funny,1358983979,1970-01-01 00:00:01.358983979
465551,138446,3086,scary,1358984001,1970-01-01 00:00:01.358984001
465552,138446,3489,Peter Pan,1358983822,1970-01-01 00:00:01.358983822
465553,138446,3489,soundtrack,1358983822,1970-01-01 00:00:01.358983822
465554,138446,3489,visually appealing,1358983822,1970-01-01 00:00:01.358983822
465555,138446,7045,family friendly,1358983660,1970-01-01 00:00:01.358983660
465556,138446,7045,Scary Movies To See on Halloween,1358983660,1970-01-01 00:00:01.358983660
465557,138446,7164,Peter Pan,1358983855,1970-01-01 00:00:01.358983855
465558,138446,7164,visually appealing,1358983855,1970-01-01 00:00:01.358983855
465559,138446,55999,dragged,1358983772,1970-01-01 00:00:01.358983772
465560,138446,55999,Jason Bateman,1358983778,1970-01-01 00:00:01.358983778
465561,138446,55999,quirky,1358983778,1970-01-01 00:00:01.358983778
465562,138446,55999,sad,1358983772,1970-01-01 00:00:01.358983772
465563,138472,923,rise to power,1194037967,1970-01-01 00:00:01.194037967

#### 15. Sort the tags DataFrame based on timestamp.

In [264]:
tags.sort_values(by='timestamp',ascending=False)

,userId,movieId,tag,timestamp,date
339178,102853,115149,russian mafia,1427771352,1970-01-01 00:00:01.427771352
158780,46072,6058,premonition,1427760764,1970-01-01 00:00:01.427760764
158763,46072,3409,premonition,1427760726,1970-01-01 00:00:01.427760726
288375,87797,215,Vienna,1427755801,1970-01-01 00:00:01.427755801
290535,88044,106782,profanity,1427754096,1970-01-01 00:00:01.427754096
290527,88044,106782,crime,1427753921,1970-01-01 00:00:01.427753921
290526,88044,106782,Amoral,1427753913,1970-01-01 00:00:01.427753913
290531,88044,106782,Jonah Hill,1427753849,1970-01-01 00:00:01.427753849
290530,88044,106782,inaccurate,1427753806,1970-01-01 00:00:01.427753806
290528,88044,106782,Economically Illiterate Writers,1427753739,1970-01-01 00:00:01.427753739
290533,88044,106782,Left-Wing Writers,1427753621,1970-01-01 00:00:01.427753621
290532,88044,106782,Left-Wing Propaganda,1427753266,1970-01-01 00:00:01.427753266
290529,88044,106782,ENFP,1427753147,1970-01-01 00:00:01.427753147
290534,88044,106782,Orgies,1427753111,1970-01-01 00:00:01.427753111
290536,88044,106782,unsatisfying ending,1427753000,1970-01-01 00:00:01.427753000
392904,122523,5004,party,1427752292,1970-01-01 00:00:01.427752292
392905,122523,5004,USA,1427752289,1970-01-01 00:00:01.427752289
150872,42640,115122,dark comedy,1427748808,1970-01-01 00:00:01.427748808
150871,42640,115122,comedy,1427748797,1970-01-01 00:00:01.427748797
150873,42640,115122,mockumentary,1427748778,1970-01-01 00:00:01.427748778
400106,123297,4573,CLV,1427747462,1970-01-01 00:00:01.427747462
405123,123297,118722,CLV,1427747321,1970-01-01 00:00:01.427747321
401017,123297,6481,CLV,1427747220,1970-01-01 00:00:01.427747220
400993,123297,6419,CLV,1427746864,1970-01-01 00:00:01.427746864
399877,123297,4211,CLV,1427746709,1970-01-01 00:00:01.427746709
405155,123297,128642,CLV,1427746337,1970-01-01 00:00:01.427746337
119989,28906,115149,cheesy,1427746074,1970-01-01 00:00:01.427746074
119993,28906,115149,over the top,1427746060,1970-01-01 00:00:01.427746060
119991,28906,115149,lack of story,1427746053,1970-01-01 00:00:01.427746053
119997,28906,115149,violent,1427746031,1970-01-01 00:00:01.427746031
...,...,...,...,...,...
81445,20513,36529,usa,1136242623,1970-01-01 00:00:01.136242623
68916,16050,6898,british,1136039368,1970-01-01 00:00:01.136039368
68918,16050,6898,harsh,1136039368,1970-01-01 00:00:01.136039368
68917,16050,6898,drugs,1136039368,1970-01-01 00:00:01.136039368
68919,16050,7060,christian,1136039301,1970-01-01 00:00:01.136039301
68922,16050,7060,religious,1136039301,1970-01-01 00:00:01.136039301
68920,16050,7060,kitsch,1136039301,1970-01-01 00:00:01.136039301
68921,16050,7060,musical,1136039301,1970-01-01 00:00:01.136039301
68924,16050,38886,eighties,1136036612,1970-01-01 00:00:01.136036612
68928,16050,38886,twee,1136036612,1970-01-01 00:00:01.136036612
68926,16050,38886,new york,1136036612,1970-01-01 00:00:01.136036612
68927,16050,38886,overrated,1136036612,1970-01-01 00:00:01.136036612
68925,16050,38886,family,1136036612,1970-01-01 00:00:01.136036612
15926,3797,8573,Nonlinear Surrealism,1135936223,1970-01-01 00:00:01.135936223
256663,75141,4642,Terrible,1135688095,1970-01-01 00:00:01.135688095
15903,3797,110,overrated,1135589075,1970-01-01 00:00:01.135589075
333944,100371,6016,brazil,1135429520,1970-01-01 00:00:01.135429520
333930,100371,2329,edward norton,1135429508,1970-01-01 00:00:01.135429508
333931,100371,2329,fuckoff nazi,1135429508,1970-01-01 00:00:01.135429508
333933,100371,2858,kevin spacey,1135429466,1970-01-01 00:00:01.135429466
333920,100371,32,bruce willis,1135429442,1970-01-01 00:00:01.135429442
333936,100371,4011,brad pitt,1135429431,1970-01-01 00:00:01.135429431
333937,100371,4011,guy ritchie,1135429431,1970-01-01 00:00:01.135429431
333922,100371,47,morgan freeman,1135429412,1970-01-01 00:00:01.135429412
333921,100371,47,brad pitt,1135429412,1970-01-01 00:00:01.135429412
333939,100371,5004,peter sellers,1135429399,1970-01-01 00:00:01.135429399
333923,100371,1193,jack nicholson,1135429371,1970-01-01 00:00:01.135429371
333924,100371,1206,stanley kubrick,1135429248,1970-01-01 00:00:01.135429248
333927,100371,1732,coen brothers,1135429236,1970-01-01 00:00:01.135429236
333932,100371,2788,monty python,1135429210,1970-01-01 00:00:01.135429210